version: 2.0.0-Beta9
apkFileName: com.android.development_settings.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
sdkInfo:
  minSdkVersion: '14'
  targetSdkVersion: '19'
packageInfo:
  forced-package-id: '127'
versionInfo:
  versionCode: '1'
  versionName: '1.0'
compressionType: false
